apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wk-auth-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wk-auth
    spec:
      containers:
        - name: wk-auth
          image: wka4docker/wk-auth
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
