apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wk-tts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wk-tts
    spec:
      containers:
        - name: wk-tts
          image: wka4docker/wk-tts
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
