apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wk-todos-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wk-todos
    spec:
      containers:
        - name: wk-todos
          image: wka4docker/wk-todos
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
