apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-auth-svc
  name: wk-auth-svc
  namespace: default
spec:
  ports:
    - name: "10084"
      port: 10084
      targetPort: 80
  selector:
    io.kompose.service: wk-auth-svc
status:
  loadBalancer: {}
