apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-blog-svc
  name: wk-blog-svc
  namespace: default
spec:
  replicas: 1
  selector:
    io.kompose.service: wk-blog-svc
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/openshift-microservices-wk-net: "true"
        io.kompose.service: wk-blog-svc
    spec:
      containers:
        - env:
            - name: MONGODB_PASSWORD
              value: example
            - name: MONGODB_SERVER
              value: mongodb://mongo-db:27017/
            - name: MONGODB_USERNAME
              value: root
          image: ' '
          name: wk-blog-svc
          ports:
            - containerPort: 80
              hostPort: 10082
              protocol: TCP
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - wk-blog-svc
        from:
          kind: ImageStreamTag
          name: wk-blog-svc:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
