apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-cognitive-svc
  name: wk-cognitive-svc
  namespace: default
spec:
  replicas: 1
  selector:
    io.kompose.service: wk-cognitive-svc
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/openshift-microservices-wk-net: "true"
        io.kompose.service: wk-cognitive-svc
    spec:
      containers:
        - env:
            - name: ServiceSettings__GrpcServerHost
              value: wk-tts-svc
            - name: ServiceSettings__GrpcServerPort
              value: "8080"
          image: ' '
          name: wk-cognitive-svc
          ports:
            - containerPort: 80
              hostPort: 10081
              protocol: TCP
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - wk-cognitive-svc
        from:
          kind: ImageStreamTag
          name: wk-cognitive-svc:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
