apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-cognitive-svc
  name: wk-cognitive-svc
  namespace: default
spec:
  ports:
    - name: "10081"
      port: 10081
      targetPort: 80
  selector:
    io.kompose.service: wk-cognitive-svc
status:
  loadBalancer: {}
