apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-sentiment-svc
  name: wk-sentiment-svc
  namespace: default
spec:
  ports:
    - name: "10083"
      port: 10083
      targetPort: 80
  selector:
    io.kompose.service: wk-sentiment-svc
status:
  loadBalancer: {}
