apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wk-todos-svc
  name: wk-todos-svc
  namespace: default
spec:
  ports:
    - name: "10080"
      port: 10080
      targetPort: 80
  selector:
    io.kompose.service: wk-todos-svc
status:
  loadBalancer: {}
